version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: role_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: role_user
      POSTGRES_PASSWORD: role_pass
      POSTGRES_DB: role_node
    ports:
      - "5432:5432"
    volumes:
      - role_postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.4
    container_name: role_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: role_user
      MYSQL_PASSWORD: role_pass
    ports:
      - "3306:3306"
    volumes:
      - role_mysql_data:/var/lib/mysql

volumes:
  role_postgres_data:
  role_mysql_data:
