import { Router } from "express";

import { ROUTE_SEGMENTS } from "../../shared/http/routes.js";
import { collectionsController } from "./collections.controller.js";

export const collectionsRouter = Router({ mergeParams: true });

collectionsRouter.get(
  ROUTE_SEGMENTS.collections.list,
  collectionsController.list,
);
collectionsRouter.get(
  ROUTE_SEGMENTS.collections.byId,
  collectionsController.getById,
);
collectionsRouter.post(
  ROUTE_SEGMENTS.collections.create,
  collectionsController.create,
);
collectionsRouter.patch(
  ROUTE_SEGMENTS.collections.byId,
  collectionsController.update,
);
collectionsRouter.delete(
  ROUTE_SEGMENTS.collections.byId,
  collectionsController.remove,
);
collectionsRouter.get(
  ROUTE_SEGMENTS.collections.endpoints,
  collectionsController.listEndpoints,
);
collectionsRouter.get(
  ROUTE_SEGMENTS.collections.endpointById,
  collectionsController.getEndpointById,
);
collectionsRouter.post(
  ROUTE_SEGMENTS.collections.endpoints,
  collectionsController.createEndpoint,
);
collectionsRouter.patch(
  ROUTE_SEGMENTS.collections.endpointById,
  collectionsController.updateEndpoint,
);
collectionsRouter.delete(
  ROUTE_SEGMENTS.collections.endpointById,
  collectionsController.removeEndpoint,
);
collectionsRouter.get(
  ROUTE_SEGMENTS.collections.endpointExamples,
  collectionsController.listEndpointExamples,
);
collectionsRouter.post(
  ROUTE_SEGMENTS.collections.endpointExamples,
  collectionsController.createEndpointExample,
);
collectionsRouter.patch(
  ROUTE_SEGMENTS.collections.endpointExampleById,
  collectionsController.updateEndpointExample,
);
collectionsRouter.delete(
  ROUTE_SEGMENTS.collections.endpointExampleById,
  collectionsController.removeEndpointExample,
);
collectionsRouter.get(
  ROUTE_SEGMENTS.collections.folders,
  collectionsController.listFolders,
);
collectionsRouter.post(
  ROUTE_SEGMENTS.collections.folders,
  collectionsController.createFolder,
);
collectionsRouter.patch(
  ROUTE_SEGMENTS.collections.folderById,
  collectionsController.updateFolder,
);
collectionsRouter.delete(
  ROUTE_SEGMENTS.collections.folderById,
  collectionsController.removeFolder,
);
